##########
#R CODE FOR COHORT CHANGE RATIO-BASED STABLE POPULATION REVIEW SHINY APP - JUST NASCENT WORK, STILL FIGURING/LEARNING AND CHECKING
#
#EDDIE HUNSINGER, AUGUST 2019 (UPDATED OCTOBER 2019)
#https://edyhsgr.github.io/eddieh/
##########

#SEE: https://u.demog.berkeley.edu/~eddieh/CCRStable/app.R 
